apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: discovery-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: discovery-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 50